name: Build and Deploy Dashboard Website

on:
  push:
    branches:
      - main  # Triggers every time you push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-module-version: '3.11'

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Python Script to Generate HTML Website
        run: python build_dashboard.py

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Uploads the folder containing the newly built index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
